# Generated by Django 4.1.5 on 2023-02-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('equipo', models.CharField(max_length=25)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='equipos',
            name='presupuesto',
            field=models.IntegerField(default=150000),
        ),
    ]
