# Generated by Django 4.1.5 on 2023-02-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_jugador_equipos_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='foto',
            field=models.CharField(default='noProcede', max_length=100),
        ),
    ]
