# Generated by Django 4.1.5 on 2023-02-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_jugador_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(default='banquillo', max_length=25),
        ),
    ]
