# Generated by Django 4.1.5 on 2023-02-19 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_jugador_equipo_alter_jugador_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.equipos')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.jugador')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.liga')),
            ],
        ),
    ]
