# Generated by Django 4.1.5 on 2023-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_equipojugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='presupuesto',
            field=models.IntegerField(default=150000000),
        ),
    ]
