# Generated by Django 4.1.5 on 2023-03-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_jornada'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='puntuacion',
            field=models.FloatField(default=0.0),
        ),
    ]
