# Generated by Django 4.1.5 on 2023-03-17 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_equipos_puntuacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='actualizar',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
