# Generated by Django 4.1.5 on 2023-03-18 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_equipos_actualizar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='actualizar',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
