# Generated by Django 4.1.5 on 2023-04-05 17:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_equipos_actualizar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='actualizar',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jugadores_ofrece', models.ManyToManyField(related_name='jugadores_ofrece+', to='authentication.jugador')),
                ('jugadores_recibe', models.ManyToManyField(related_name='jugadores_recibe+', to='authentication.jugador')),
                ('usuario_ofrece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_ofrece', to='authentication.equipos')),
                ('usuario_recibe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_recibe', to='authentication.equipos')),
            ],
        ),
    ]
