# Generated by Django 4.1.5 on 2023-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_equipos_actualizar_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipojugador',
            name='posicion',
            field=models.CharField(choices=[('POR', 'PORTERO'), ('LI', 'LATERAL IZQUIERDO'), ('LD', 'LATERAL DERECHO'), ('DFCD', 'DEFENSA CENTRAL DERECHO'), ('DFCI', 'DEFENSA CENTRAL IZQUIERDO'), ('MCD', 'CENTROCAMPISTA DEFENSIVO'), ('MI', 'CENTROCAMPISTA IZQUIERDO'), ('MD', 'CENTROCAMPISTA DERECHO'), ('DC', 'DELANTERO CENTRO'), ('EI', 'EXTREMO IZQUIERDO'), ('ED', 'EXTREMO DERECHO'), ('SUS', 'BANQUILLO')], default='SUS', max_length=50),
        ),
    ]
