# Generated by Django 4.1.5 on 2023-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liga',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
